### ISSUE TITLE
Support roapi for AWS Lambda

### ISSUE THREAD

**Issue by linrium** [roapi/roapi#34]
I want to use roapi for serverless but I have to do some tricks. For example, I've to build a python image, and run roapi as a subprocess then use restful API to call it. I checked the repo and saw the subproject `columnq`. So do you have any plan to split `columnq` to another repo so that it would be easy to use in serverless or integrate with another backend code?

**Why support serverless?**
In my company, we have a lot of teams. Each team has different resources, so I want them can take the initiative to select their resources. When they invoke the serverless function, it will create a YAML config (with their resources) in lambda `tmp` direction and another subprocess for roapi will be invoked by reading this config.

**How to contribute?**
If you have a plan to support serverless, then how can I help you to contribute it? I'm also excited about this project.

Docker image:
```dockerfile
FROM public.ecr.aws/lambda/python:3.8
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt
CMD ["/app/app.hello"]
```

Check roapi is running:
```python
def start_roapi(addr, config_file_name):
    process = subprocess.Popen([
        "roapi-http -c {filename}".format(filename=config_file_name)],
        shell=True,
        # stdout=subprocess.PIPE,
        # stderr=subprocess.PIPE
    )

    url = "http://{addr}".format(addr=addr)
    for n in range(1000):
        try:
            time.sleep(0.5)
            res = requests.request("GET", url)
            print("started", res.text)
            break
        except:
            pass

    return process
```

Then, I've to query to localhost:
```python
url = "http://{addr}{path}?{qs}".format(addr=addr, path=event["rawPath"], qs=event["rawQueryString"])
response = requests.request(method, url, headers=event["headers"], data=data)
```

**Comment by thucnc** [comment]
I have the same interest with @linrium on making use of roapi for non-tech users when they have static resources and want to query them with sql. So how can we create an on-demand api to query personal resource (serverless is a good approach)? The current user guide seems not meet this use-case ?

**Comment by houqp** [comment]
I have a secret roadmap item to export columnq as libraries to other languages like python through a thin language binding. This worked really well for another project that I am working on right now, see https://github.com/delta-io/delta-rs/tree/main/python.

In preparation for that, I have already abstracted the high level interfaces into https://github.com/roapi/roapi/blob/main/columnq/src/columnq.rs#L15, I expect other language bindings to have a similar set of APIs. For example, you will be able to do something like this in python:

```python
from columnq import ColumnQ

cq = ColumnQ()
cq.load_table(uri="s3://abc.csv")
rows = cq.query_sql("SELECT * FROM table")
```

That said, I don't think columnq or roapi is a good fit for serverless because it would need to load the same static dataset on every request which results in waste of network IO and longer request handling time.

You will get the best performance and cost benefit by running it as a always on daemon, like a database, so all requests can be served through a single in memory copy of the static dataset across multiple threads. So I would recommend give services like AWS ECS fargate a try. You can also use any container orchestration systems like Kubernetes. For autoscaling, it's best to configure it to scale up/down based on CPU usage.

**Comment by houqp** [comment]
But if anyone of you is interested in working on a python binding for columnq using pyo3 and maturin, please let me know, I will be more than happy to help guide the process.

**Comment by thucnc** [comment]
> I have a secret roadmap item to export columnq as libraries to other languages like python through a thin language binding. This worked really well for another project that I am working on right now, see https://github.com/delta-io/delta-rs/tree/main/python.
> 
> In preparation for that, I have already abstracted the high level interfaces into https://github.com/roapi/roapi/blob/main/columnq/src/columnq.rs#L15, I expect other language bindings to have a similar set of APIs. For example, you will be able to do something like this in python:
> 
> ```python
> from columnq import ColumnQ
> 
> cq = ColumnQ()
> cq.load_table(uri="s3://abc.csv")
> rows = cq.query_sql("SELECT * FROM table")
> ```
> 
> That said, I don't think columnq or roapi is a good fit for serverless because it would need to load the same static dataset on every request which results in waste of network IO and longer request handling time.
> 
> You will get the best performance and cost benefit by running it as a always on daemon, like a database, so all requests can be served through a single in memory copy of the static dataset across multiple threads. So I would recommend give services like AWS ECS fargate a try. You can also use any container orchestration systems like Kubernetes. For autoscaling, it's best to configure it to scale up/down based on CPU usage.

Thanks @houqp for your suggestion. It's great to know your roadmap, and I think it would be great to use ColumnQ with streamlit :D
