### ISSUE TITLE
Failed to load Delta table with partitions

### ISSUE THREAD

**Issue by mmuru** [roapi/roapi#58]
When I tried to load a Delta table with partitions, it throws the following exception

Error: DeltaTable error: Failed to apply transaction log: Invalid JSON in log record
Caused by:
    0: Failed to apply transaction log: Invalid JSON in log record
    1: Invalid JSON in log record
    2: invalid type: null, expected a string at line 1 column 195

I believe it fails because the table commit log has an entry 
```
{"add":{"path":"file_year=__HIVE_DEFAULT_PARTITION__/file_month=__HIVE_DEFAULT_PARTITION__/part-00000-4cfe8fb8-3905-4ae6-8b44-e7612753064c.c000.snappy.parquet","partitionValues":{"file_year":null,"file_month":null},"size":3331,"modificationTime":1628075908000,"dataChange":true}}
```

**Comment by houqp** [comment]
good timing, i believe https://github.com/delta-io/delta-rs/pull/354 should fix it :)

**Comment by houqp** [comment]
@mmuru could you give it another try with the 0.3.4 release?

**Comment by mmuru** [comment]
@houqp: I tried it with 0.3.4 release and getting different exception now. 
```
Error: DataFusion error: Error during planning: Mismatch between schema and batches
Caused by:
    Error during planning: Mismatch between schema and batches
```

By the way, how to load a specific partition? Is there way filter only partition columns on the server side?

**Comment by houqp** [comment]
This is usually caused by mismatch between the schema in delta table and the underlying parquet files. Could you give https://delta-io.github.io/delta-rs/python/ or https://github.com/delta-io/delta-rs/tree/main/rust a try to see if you can reproduce this error? If you can share the delta table with me for further debugging, that would be even better, but I am guessing it contains proprietary data.

> By the way, how to load a specific partition? Is there way filter only partition columns on the server side?

delta-rs supports partition filtering (https://docs.rs/deltalake/0.4.0/deltalake/struct.DeltaTable.html#method.get_files_by_partitions), but it's not used in roapi at the moment. But it should be pretty straight forward to add a config option to support this.

**Comment by mmuru** [comment]
@houqp: I can't reproduce the error with delta-rs/python. I am already using delta lake with Spark and it worked without any issues. I think, the issues with roapi-http side. Unfortunately, I can't share the delta table but I will try to create a sample delta table to reproduce the issue. 

Sure, is there sample reference how to add a config option in roapi-http? Please, point it to me. Thanks.

**Comment by houqp** [comment]
> I can't reproduce the error with delta-rs/python

That's very interesting. Does your table have any timestamp columns? If so, are those timestamps stored in parquet as int96 or int64?

> Sure, is there sample reference how to add a config option in roapi-http? Please, point it to me. Thanks.

Similar to json and csv load options, you can add create a new struct for delta table option, then set it at https://github.com/roapi/roapi/blob/main/columnq/src/table/mod.rs#L141. In that delta table option, we could have an optional partition filter field that can be set from the config file. Then in [delta::to_mem_table](https://github.com/roapi/roapi/blob/main/columnq/src/table/delta.rs#L34), we could access the partition filter field and pass it down to https://github.com/roapi/roapi/blob/main/columnq/src/table/delta.rs#L50 (replace `get_file_uris` with [get_file_uris_by_partitions](https://docs.rs/deltalake/0.4.0/deltalake/struct.DeltaTable.html#method.get_file_uris_by_partitions)).

**Comment by alitrack** [comment]
[delta-iris_partition.zip](https://github.com/roapi/roapi/files/8511947/delta-iris_partition.zip)
here is the example, create by PySpark.

I tried python version deltalake, it works.

**Comment by leodido** [comment]
I have a partitioned Parquet dataset and I get the "Mismatch between schema and batches" errors too.

When I define `use_memory_table: false` in the ROAPI config file, the error goes away. Since this option (when false), to my understanding, instructs ROAPI to use datafusion's native file format table providers, the error should be somewhere else.
