### ISSUE TITLE
Support for large data sets (avoiding `MemTable`)

### ISSUE THREAD

**Issue by dispanser** [roapi/roapi#62]
Hi,

Related to #57, 
I have a use case where I need visualize a small part  (few thousand rows) from a large dataset (a few hundred TBs) by using a highly selective query that is typically only hitting a few parquet files out of a large number of partitions. Using spark, these queries can be served in a few seconds (assuming that the file meta data fits in memory) - even on a single-node system.

I've been playing with using datafusion directly, but actually roapi is doing exactly what I need. Is there any design choice / project direction that prevents the various table implementations from returning some `dyn TableProvider` instead of `MemTable`?

I understand that roapi supports various cloud storage systems, which is not supported by datafusion yet, but given the recent developments in https://github.com/apache/arrow-datafusion/pull/811 there is hopefully a solution coming.

FWIW, I hammered together a small PoC by ripping out the parquet loader and directly registering the parquet reader over at https://github.com/dispanser/roapi/tree/lazy-load-parquet . This approach seems to work, but is definitely not mergeable :-).

A possibly implementation could add a configuration flag that flips from `MemTable` to `TableProvider` code paths, supporting both the existing in-memory scenario as well as a new code path that would register parquet / delta / ... directly.

**Comment by houqp** [comment]
Thanks @dispanser for the PoC! I think it's a good idea to move from MemTable to the TableProvider trait generic. I will be more than happy to merge this change in if we can gate it with a config. We can let users make their own tradeoffs on whether they want low latency (memtable) v.s. larger dataset.

One feature that I think would be pretty cool to add in the future is multi-tier caching for TableProviders that requires IO on every table scan. This should help improve latency and reduce IO overhead for hot queries.

**Comment by afterthought** [comment]
It looks like Datafusion might support cloud storage now for Delta? I have started a fork to see how far I could get. Rust is new to me though. I made a little progress, but seem stuck again. delta-rs is now prefixing a delta-rs:// scheme dynamically and that is tripping up roapi. I'm not quite sure what to do next. I saw this closed issue and thought I'd ping you guys since you were close to this a couple of years back. Would anyone be able to help or guide me on a PR?

My use case involves writing a join query against a large and small Delta table. I'm trying to test this functionality. Spark has partition pruning and I don't know enough about datafusion to guess how well it could handle this use case.

**Comment by afterthought** [comment]
So I have some code changes working now. I'll open a new PR in a couple of days probably after some more testing. I already confirmed that I'm not seeing partition pruning in the execution plans. However, the performance is looking quite good despite that. So I'm excited to help get this functionality merged in.
